[package]
name = "sstv"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fftw = "0.7.0"
sndfile = "0.1.1"
image = "0.24.3"

# For later.
# tui = "0.19.0"
# crossterm = "0.25"